//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.DbRecursos", typeof(DbRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM BANCO WHERE ID=@ID.
        /// </summary>
        internal static string uspBancoDelete {
            get {
                return ResourceManager.GetString("uspBancoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM BANCO.
        /// </summary>
        internal static string uspBancoGet {
            get {
                return ResourceManager.GetString("uspBancoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO BANCO 
        ///(
        ///NOMBRE, 
        ///DIRECCION, 
        ///FECHA_REGISTRO
        ///)
        ///OUTPUT INSERTED.ID
        ///VALUES
        ///(
        ///@NOMBRE, 
        ///@DIRECCION, 
        ///@FECHA_REGISTRO).
        /// </summary>
        internal static string uspBancoInsert {
            get {
                return ResourceManager.GetString("uspBancoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE BANCO SET 
        ///NOMBRE=@NOMBRE,DIRECCION=@DIRECCION,FECHA_REGISTRO=@FECHA_REGISTRO
        ///WHERE ID=@ID.
        /// </summary>
        internal static string uspBancoUpdate {
            get {
                return ResourceManager.GetString("uspBancoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM ESTADO.
        /// </summary>
        internal static string uspEstadoGet {
            get {
                return ResourceManager.GetString("uspEstadoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM MONEDA.
        /// </summary>
        internal static string uspMonedaGet {
            get {
                return ResourceManager.GetString("uspMonedaGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM ORDEN_PAGO WHERE ID=@ID.
        /// </summary>
        internal static string uspOrdenPagoDelete {
            get {
                return ResourceManager.GetString("uspOrdenPagoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///ORDEN_PAGO.*,
        ///BANCO.NOMBRE AS BANCO_NOMBRE,
        ///BANCO.ID AS BANCO_ID,
        ///MONEDA.NOMBRE AS MONEDA_NOMBRE,
        ///ESTADO.NOMBRE AS ESTADO_NOMBRE,
        ///MONEDA.CODIGO AS MONEDA_CODIGO,
        ///ESTADO.CODIGO AS ESTADO_CODIGO,
        ///SUCURSAL.NOMBRE AS SUCURSAL_NOMBRE
        ///FROM ORDEN_PAGO 
        ///INNER JOIN SUCURSAL  ON ORDEN_PAGO.SUCURSAL=SUCURSAL.ID
        ///INNER JOIN BANCO ON BANCO.ID=SUCURSAL.BANCO
        ///INNER JOIN MONEDA  ON ORDEN_PAGO.MONEDA=MONEDA.ID
        ///INNER JOIN ESTADO  ON ORDEN_PAGO.ESTADO=ESTADO.ID.
        /// </summary>
        internal static string uspOrdenPagoGet {
            get {
                return ResourceManager.GetString("uspOrdenPagoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into ORDEN_PAGO
        ///(
        ///SUCURSAL,
        ///MONTO,
        ///MONEDA,
        ///ESTADO,
        ///FECHA_PAGO
        ///) OUTPUT INSERTED.ID 
        ///VALUES(
        ///@SUCURSAL,
        ///@MONTO,
        ///@MONEDA,
        ///@ESTADO,
        ///@FECHA_PAGO
        ///).
        /// </summary>
        internal static string uspOrdenPagoInsert {
            get {
                return ResourceManager.GetString("uspOrdenPagoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE BANCO SET 
        ///NOMBRE=@NOMBRE,DIRECCION=@DIRECCION,FECHA_REGISTRO=@FECHA_REGISTRO
        ///WHERE ID=@ID.
        /// </summary>
        internal static string uspOrdenPagoUpdate {
            get {
                return ResourceManager.GetString("uspOrdenPagoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM SUCURSAL WHERE ID=@ID.
        /// </summary>
        internal static string uspSucursalDelete {
            get {
                return ResourceManager.GetString("uspSucursalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///SUCURSAL.*,
        ///BANCO.NOMBRE AS BANCO_NOMBRE,
        ///BANCO.DIRECCION AS BANCO_DIRECCION,
        ///BANCO.FECHA_REGISTRO AS BANCO_FECHA_REGISTRO
        ///FROM SUCURSAL 
        ///INNER JOIN BANCO  ON BANCO.ID=SUCURSAL.BANCO.
        /// </summary>
        internal static string uspSucursalGet {
            get {
                return ResourceManager.GetString("uspSucursalGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO SUCURSAL 
        ///(
        ///NOMBRE, 
        ///DIRECCION, 
        ///FECHA_REGISTRO,
        ///BANCO
        ///) OUTPUT INSERTED.ID 
        ///VALUES
        ///(
        ///@NOMBRE, 
        ///@DIRECCION, 
        ///@FECHA_REGISTRO,
        ///@BANCO
        ///).
        /// </summary>
        internal static string uspSucursalInsert {
            get {
                return ResourceManager.GetString("uspSucursalInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE SUCURSAL SET 
        ///NOMBRE=@NOMBRE,DIRECCION=@DIRECCION,FECHA_REGISTRO=@FECHA_REGISTRO,SUCURSAL=@SUCURSAL, BANCO=@BANCO
        ///WHERE ID=@ID.
        /// </summary>
        internal static string uspSucursalUpdate {
            get {
                return ResourceManager.GetString("uspSucursalUpdate", resourceCulture);
            }
        }
    }
}
